associates/urls.py
from django.urls import path

from . import views

app_name = 'associates'

urlpatterns = [
    path('', views.AssociateListView.as_view(), name='associate-list'),
    path('create/', views.AssociateCreateView.as_view(),
         name='associate-create'),
    path('<int:pk>/', views.AssociateDetailView.as_view(),
         name='associate-detail'),
    path('<int:pk>/update/', views.AssociateUpdateView.as_view(),
         name='associate-update'),
    path('<int:pk>/delete/', views.AssociateDeleteView.as_view(),
         name='associate-delete')
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('associates/', include('associates.urls', namespace='associates')),

    # Reset password
    path('reset-password/', PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html',
        success_url=reverse_lazy('password-reset-done'),
        email_template_name='password_reset/password_reset_email.html'),
         name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='password_reset/password_reset_done.html'),
         name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='password_reset/password_reset_confirm.html',
             success_url=reverse_lazy('password-reset-complete')),
         name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),
         name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

associates/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_associate = models.BooleanField(default=False)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.get_full_name()


class UserDepartment(models.Model):
    """ Model to store the organizer information for associates.  """
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username.title()


class Associate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey('UserDepartment', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Associate'
        verbose_name_plural = 'Associates'
        ordering = ('id',)

    def __str__(self):
        return self.user.email

    def get_absolute_url(self):
        return reverse('associates:associate-detail', kwargs={'pk': self.pk})

associates/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class AssociateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set first_name and last_name as required fields
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True    

associates/views.py
import random

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .forms import AssociateForm
from .mixins import OrganizerAndLoginRequiredMixin, AssociateMixin
from .models import Associate


class AssociateListView(OrganizerAndLoginRequiredMixin, AssociateMixin,
                        generic.ListView):
    """View for listing Associate instances."""
    template_name = 'associates/associate_list.html'
    context_object_name = 'associates'


class AssociateCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    """View for creating a new Associate instance."""
    template_name = 'associates/associate_create.html'
    form_class = AssociateForm

    def get_success_url(self):
        return reverse('associates:associate-list')

    def form_valid(self, form):
        """ Create associate and set the department regarding the organizer """
        user = form.save(commit=False)
        user.is_associate = True
        user.is_organizer = False
        user.set_password(f'{random.randint(0, 1000000)}')
        user.save()
        # Creates a new Associate instance
        associate = Associate.objects.create(
            user=user,
            department=self.request.user.userdepartment
        )
        messages.success(self.request,
                         f'Associate {associate} was created successfully.')
        return super().form_valid(form)

    def send_invitation_email(self, user):
        """ Sends an invitation email to the new Associate. """
        send_mail(
            subject='You are invited to be an associate.',
            message=f'You were added as an associate on CRM. '
                    f'Temporary password is: {user.password}.',
            from_email='django@crm.com',
            recipient_list=[user.email]
        )


class AssociateDetailView(OrganizerAndLoginRequiredMixin, AssociateMixin,
                          generic.DetailView):
    """View for displaying details of an Associate instance."""
    template_name = 'associates/associate_detail.html'
    context_object_name = 'associate'


class AssociateUpdateView(OrganizerAndLoginRequiredMixin, AssociateMixin,
                          generic.UpdateView):
    """View for updating Associate details."""
    template_name = 'associates/associate_update.html'
    form_class = AssociateForm
    context_object_name = 'associate'

    def get(self, request, *args, **kwargs):
        """
        Retrieves the Associate and populates the form with existing data.
        """
        associate = get_object_or_404(Associate, id=self.kwargs['pk'])
        form = self.form_class(instance=associate.user)
        return self.render_to_response({'form': form, 'associate': associate})

    def form_valid(self, form):
        """ Updates the User model fields and displays success messages. """
        associate = get_object_or_404(Associate, id=self.kwargs['pk'])

        user = associate.user
        user.email = form.cleaned_data['email']
        user.username = form.cleaned_data['username']
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()
        messages.success(self.request, 'Associate data was updated successfully.')

        return super().form_valid(form)


class AssociateDeleteView(OrganizerAndLoginRequiredMixin, AssociateMixin,
                          SuccessMessageMixin, generic.DeleteView):
    """View for deleting an Associate instance."""
    template_name = 'associates/associate_delete.html'
    context_object_name = 'associate'
    success_message = 'Associate was deleted successfully.'
    

associates/templates/associates/associate_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">

    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'associates:associate-list' %}">Go back to associates</a>
    </div>

    <h1 class="text-4xl text-gray-800">Create a new associate</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>

</div>
{% endblock content %}

associates/templates/associates/associate_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'associates:associate-list' %}">Go back to associates</a>
    </div>
    <h1 class="text-3xl text-gray-800">Are you sure you want to delete this associate?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
    <div class="py-5 mt-5">
        <a class="hover:text-blue-500" href="{{ associate.get_absolute_url }}">Cancel</a>
    </div>
</div>
{% endblock content %}

associates/templates/associates/associate_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">ASSOCIATE</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ associate.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{{ associate.get_absolute_url }}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'associates:associate-update' associate.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ associate.user|title }} </span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ associate.user.email }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Username</span>
                <span class="ml-auto text-gray-900">{{ associate.user.username }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

associates/templates/associates/associate_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Associates</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'associates:associate-create' %}">Create a new associate</a>
                </div>
            </div>

            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Full Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for associate in associates %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ associate.user.first_name|title }} {{ associate.user.last_name|title }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ associate.user.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'associates:associate-update' associate.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}

                            <p>There are currently no associates</p>

                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>
{% endblock content %}

associates/templates/associates/associate_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">ASSOCIATE</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ associate.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{{associate.get_absolute_url}}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'associates:associate-update' associate.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'associates:associate-delete' associate.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}