crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('associates/', include('associates.urls', namespace='associates')),

    # Reset password
    path('reset-password/', PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html',
        success_url=reverse_lazy('password-reset-done'),
        email_template_name='password_reset/password_reset_email.html'),
         name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='password_reset/password_reset_done.html'),
         name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='password_reset/password_reset_confirm.html',
             success_url=reverse_lazy('password-reset-complete')),
         name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),
         name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path

from . import views

app_name = 'tickets'

urlpatterns = [
    # Ticket views
    path('', views.TicketListView.as_view(), name='ticket-list'),
    path('create/', views.TicketCreateView.as_view(), name='ticket-create'),
    path('<int:pk>/', views.TicketDetailView.as_view(), name='ticket-detail'),
    path('<int:pk>/update/', views.TicketUpdateView.as_view(),
         name='ticket-update'),
    path('<int:pk>/delete/', views.TicketDeleteView.as_view(),
         name='ticket-delete'),
    path('<int:pk>/assign-associate/', views.AssignAssociateView.as_view(),
         name='assign-associate'),
    path('<int:pk>/category/', views.TicketCategoryUpdateView.as_view(),
         name='ticket-category-update'),

    # FollowUp views
    path('<int:pk>/followups/create/', views.FollowUpCreateView.as_view(),
         name='ticket-followup-create'),
    path('followups/<int:pk>/update/', views.FollowUpUpdateView.as_view(),
         name='ticket-followup-update'),
    path('followups/<int:pk>/delete/', views.FollowUpDeleteView.as_view(),
         name='ticket-followup-delete'),

    # Category views
    path('categories/', views.CategoryListView.as_view(),
         name='category-list'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(),
         name='category-detail'),
    path('create-category/', views.CategoryCreateView.as_view(),
         name='category-create'),

    # JSON view
    path('json/', views.TicketJsonView.as_view(), name='ticket-list-json'),
]

tickets/models.py
import os

from django.db import models
from django.urls import reverse

from associates.models import Associate, UserDepartment


class TicketManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


TICKET_TYPES = (
    (1, 'Type 1'),
    (2, 'Type 2'),
    (3, 'Type 3')
)

CATEGORIES = (
    ('assigned', 'Assigned'),
    ('work_in_progress', 'Work in Progress'),
    ('processed', 'Processed'),
    ('completed', 'Completed'),
    ('returned', 'Returned')
)


def ticket_upload_files(instance, filename):
    """Generates the file path for ticket files based on ticket ID."""
    return os.path.join('ticket_files', f'ticket_{instance.id}', filename)


class Ticket(models.Model):
    title = models.CharField(max_length=150)
    type = models.IntegerField(choices=TICKET_TYPES)
    description = models.TextField(default='Describe your task here.')
    uploaded_file = models.FileField(null=True, blank=True,
                                     upload_to=ticket_upload_files)
    uploaded_image = models.ImageField(null=True, blank=True,
                                       upload_to=ticket_upload_files)
    created_date = models.DateTimeField(auto_now_add=True)
    completed_date = models.DateTimeField(null=True, blank=True)

    department = models.ForeignKey(UserDepartment, on_delete=models.CASCADE)
    associate = models.ForeignKey(Associate, on_delete=models.SET_NULL,
                                  related_name='associates', null=True,
                                  blank=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,
                                 related_name='categories', null=True,
                                 blank=True)

    objects = TicketManager()

    class Meta:
        verbose_name = 'Ticket'
        verbose_name_plural = 'Tickets'
        ordering = ('-created_date',)

    def __str__(self):
        return f'{self.title}, id: {self.pk}'

    def get_absolute_url(self):
        return reverse('tickets:ticket-detail', kwargs={'pk': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=30, choices=CATEGORIES, unique=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('id',)

    def __str__(self):
        return self.get_name_display()

    def get_absolute_url(self):
        return reverse('tickets:category-detail', kwargs={'pk': self.pk})


def upload_follow_ups(instance, filename):
    return f'ticket_files/ticket_{instance.ticket.id}/ticket_followups/{filename}'


class FollowUp(models.Model):
    ticket = models.ForeignKey(Ticket, related_name='followups',
                               on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True, null=True)
    file = models.FileField(null=True, blank=True, upload_to=upload_follow_ups)

    class Meta:
        verbose_name = 'FollowUp'
        verbose_name_plural = 'FollowUps'
        ordering = ('-created_date',)

    def __str__(self):
        return f'Ticket id: {self.ticket.id} FollowUp'

tickets/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.db.models import Count, Q
from django.forms import ValidationError
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from associates.mixins import OrganizerAndLoginRequiredMixin
from .forms import (TicketForm, AssignAssociateForm, TicketCategoryUpdateForm,
                    FollowUpForm, CategoryForm)
from .mixins import TicketFormAndUrlMixin, TicketQuerysetMixin, FollowUpMixin
from .models import Ticket, Category


class TicketCreateView(TicketFormAndUrlMixin, OrganizerAndLoginRequiredMixin,
                       generic.CreateView):
    """ View for creating a new ticket. """
    template_name = 'tickets/ticket/ticket_create.html'
    form_class = TicketForm

    def form_valid(self, form):
        ticket = form.save(commit=False)

        # Set the ticket department
        ticket.department = self.request.user.userdepartment
        ticket.save()
        send_mail(
            subject='A ticket has been created.',
            message='Go to the site to see the new ticket.',
            from_email='test@test.com',
            recipient_list=['associate@test.com']
        )
        messages.success(self.request,
                         'You have successfully created a ticket.')
        return super().form_valid(form)


class TicketListView(LoginRequiredMixin, generic.ListView):
    """ 
    View for displaying a list of tickets. 
    
    For organizer display all tickets assigned and unassigned to associates
    regarding the user's department.
    For associate display only tickets assigned to the specific user.
    """
    template_name = 'tickets/ticket/ticket_list.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            # Show tickets assigned to associates within their department
            queryset = Ticket.objects.filter(
                department=user.userdepartment,
                associate__isnull=False
            )
        else:
            # Show only tickets assigned to the specific associate
            queryset = Ticket.objects.filter(
                department=user.associate.department,
                associate__isnull=False
            )
            # Filter tickets regarding the specific associate           
            queryset = queryset.filter(associate__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            # For organizers, include a list of unassigned tickets
            queryset = Ticket.objects.filter(
                department=user.userdepartment,
                associate__isnull=True
            )
            context.update({'unassigned_tickets': queryset})
        return context


class TicketDetailView(TicketQuerysetMixin, LoginRequiredMixin,
                       generic.DetailView):
    """ View for ticket details. """
    template_name = 'tickets/ticket/ticket_detail.html'
    context_object_name = 'ticket'


class TicketUpdateView(TicketFormAndUrlMixin, OrganizerAndLoginRequiredMixin,
                       generic.UpdateView):
    """
    View for updating a ticket.

    Organizer can update tickets for the entire department.
    Associate is forbidden to update tickets.
    """
    template_name = 'tickets/ticket/ticket_update.html'
    form_class = TicketForm
    context_object_name = 'ticket'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            # For organizers, show all tickets in the user's department
            queryset = Ticket.objects.filter(department=user.userdepartment)
        else:
            # For associates, forbid ticket updates by providing an empty queryset
            queryset = Ticket.objects.none()
        return queryset

    def form_valid(self, form):
        """
        If the ticket category is set to 'completed', update the completion date.
        """
        ticket_before_update = self.get_object()
        ticket = form.save(commit=False)
        completed_category = Category.objects.get(name='completed')

        if form.cleaned_data['category'] == completed_category:
            # Update the date at which this ticket was completed
            if ticket_before_update.category != completed_category:
                # This ticket has now been completed
                ticket.completed_date = datetime.datetime.now()
        ticket.save()
        messages.info(self.request,
                      'You have successfully updated this ticket')
        return super().form_valid(form)


class TicketDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    """
    View for deleting a ticket.
    
    Organizer can delete tickets for the entire department.
    Associate is forbidden to delete tickets.
    """
    template_name = 'tickets/ticket/ticket_delete.html'

    def get_success_url(self):
        return reverse('tickets:ticket-list')

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            # For organizers, show all tickets in the user's department
            queryset = Ticket.objects.filter(department=user.userdepartment)
        else:
            # For associates, forbid ticket deletion by providing an empty queryset
            queryset = Ticket.objects.none()
        return queryset


class TicketCategoryUpdateView(TicketQuerysetMixin, LoginRequiredMixin,
                               generic.UpdateView):
    """
    View for updating the category of a ticket.

    Organizer can update the category for tickets in their department.
    Associate can only update the category for their own assigned tickets.
    """
    template_name = 'tickets/ticket/ticket_category_update.html'
    form_class = TicketCategoryUpdateForm
    context_object_name = 'ticket'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """ 
        If the ticket category is set to 'completed', update the completion date.
        If the associate is not selected before assigning the category, raise
        a validation error and redirect with an error message.
        """
        ticket_before_update = self.get_object()
        instance = form.save(commit=False)
        completed_category = Category.objects.get(name='completed')

        # Check if the associate is selected
        try:
            if instance.associate is None:
                raise ValidationError(
                    'Associate must be selected before assigning a category.')
        except ValidationError as e:
            # Handle the validation error by redirecting back to the form
            # with an error message
            messages.error(self.request, str(*e))
            return redirect(reverse_lazy('tickets:ticket-category-update',
                                         kwargs={'pk': self.get_object().id}))

        if form.cleaned_data['category'] == completed_category:
            # Update the date at which this ticket was completed
            if ticket_before_update.category != completed_category:
                # This ticket has now been completed
                instance.completed_date = datetime.datetime.now()
        instance.save()
        messages.info(self.request,
                      'You have successfully updated this ticket')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tickets:ticket-detail',
                       kwargs={'pk': self.get_object().id})


class AssignAssociateView(TicketFormAndUrlMixin,
                          OrganizerAndLoginRequiredMixin, generic.FormView):
    """ View for assigning an associate to a ticket. """
    template_name = 'tickets/ticket/assign_associate.html'
    form_class = AssignAssociateForm

    def form_valid(self, form):
        # Retrieve the existing ticket
        ticket = Ticket.objects.get(id=self.kwargs['pk'])

        # Update the ticket with the selected associate
        ticket.associate = form.cleaned_data['associate']

        # Check if the 'assigned' category exists, create it if not
        assigned_category, created = Category.objects.get_or_create(name='assigned')
        
        if ticket.associate:
            # If an associate is selected, set the ticket category to 'assigned'
            ticket.category = assigned_category

        ticket.save()

        return super().form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    """ 
    View for displaying a list of ticket categories.

    For organizer display categories for their department.
    For associate display categories for their assigned tickets.
    """
    template_name = 'tickets/category/category_list.html'
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        # Filter tickets based on the user's role and department
        if user.is_organizer:
            tickets = Ticket.objects.filter(department=user.userdepartment)
        else:
            tickets = Ticket.objects.filter(
                department=user.associate.department, associate=user.associate)

        # Count how many tickets are in each category based on the organizer 
        categories = self.get_queryset()
        category_counts = categories.annotate(count=Count('categories',
                            filter=Q(categories__in=tickets))).order_by('id')

        # Count how many tickets are unassigned        

tickets/templates/tickets/category/category_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'tickets:category-list' %}">Go back to categories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new category</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

tickets/templates/tickets/category/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
            {{ category.name|title }}
        </h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These are the tickets under this category
        </p>
        <a class="hover:text-blue-500" href="{% url 'tickets:category-list' %}">Go back to categories</a>        
      </div>      
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                ID
              </th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                Title
              </th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                Type
              </th>             
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                Created Date
              </th>             
            </tr>
          </thead>
          <tbody>
            {% for ticket in tickets %}
              <tr>
                <td class="px-4 py-3">{{ ticket.id }}</td>
                <td class="px-4 py-3">
                  <a class="hover:text-blue-500" href="{{ ticket.get_absolute_url }}">{{ ticket.title }}</a>
                </td>
                <td class="px-4 py-3">{{ ticket.get_type_display }}</td>                  
                <td class="px-4 py-3">{{ ticket.created_date }}</td>                  
              </tr>
            {% empty %}  
            <p>There are no tickets for this category yet.</p>
            <br>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

tickets/templates/tickets/category/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These categories segment the tickets
        </p>
        {% if request.user.is_organizer %}
          <a href="{% url 'tickets:category-create' %}" class="hover:text-blue-500">Create a category</a>
        {% endif %}
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">Ticket Count</th>
            </tr>
          </thead>
          <tbody>
            {% if user.is_organizer %}          
            <tr>
                <td class="px-4 py-3">Unassigned</td>
                <td class="px-4 py-3">{{ unassigned_ticket_count }}</td>
            </tr>
            {% endif %}
            
            {% for category in category_counts %}
            <tr>
              <td class="px-4 py-3">
                <a href="{% url 'tickets:category-detail' category.pk %}" class="hover:text-blue-500">{{ category.get_name_display }}</a>
              </td>
              <td class="px-4 py-3">{{ category.count }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}