associates/urls.py
from django.urls import path

from . import views

app_name = 'associates'

urlpatterns = [
    path('', views.AssociateListView.as_view(), name='associate-list'),
    path('create/', views.AssociateCreateView.as_view(),
         name='associate-create'),
    path('<int:pk>/', views.AssociateDetailView.as_view(),
         name='associate-detail'),
    path('<int:pk>/update/', views.AssociateUpdateView.as_view(),
         name='associate-update'),
    path('<int:pk>/delete/', views.AssociateDeleteView.as_view(),
         name='associate-delete')
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('associates/', include('associates.urls', namespace='associates')),

    # Reset password
    path('reset-password/', PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html',
        success_url=reverse_lazy('password-reset-done'),
        email_template_name='password_reset/password_reset_email.html'),
         name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='password_reset/password_reset_done.html'),
         name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='password_reset/password_reset_confirm.html',
             success_url=reverse_lazy('password-reset-complete')),
         name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),
         name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView 
    
from .import views

app_name = 'landing'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing-page'), 
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'), 
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='landing/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout')   
]

tickets/urls.py
from django.urls import path

from . import views

app_name = 'tickets'

urlpatterns = [
    # Ticket views
    path('', views.TicketListView.as_view(), name='ticket-list'),
    path('create/', views.TicketCreateView.as_view(), name='ticket-create'),
    path('<int:pk>/', views.TicketDetailView.as_view(), name='ticket-detail'),
    path('<int:pk>/update/', views.TicketUpdateView.as_view(),
         name='ticket-update'),
    path('<int:pk>/delete/', views.TicketDeleteView.as_view(),
         name='ticket-delete'),
    path('<int:pk>/assign-associate/', views.AssignAssociateView.as_view(),
         name='assign-associate'),
    path('<int:pk>/category/', views.TicketCategoryUpdateView.as_view(),
         name='ticket-category-update'),

    # FollowUp views
    path('<int:pk>/followups/create/', views.FollowUpCreateView.as_view(),
         name='ticket-followup-create'),
    path('followups/<int:pk>/update/', views.FollowUpUpdateView.as_view(),
         name='ticket-followup-update'),
    path('followups/<int:pk>/delete/', views.FollowUpDeleteView.as_view(),
         name='ticket-followup-delete'),

    # Category views
    path('categories/', views.CategoryListView.as_view(),
         name='category-list'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(),
         name='category-detail'),
    path('create-category/', views.CategoryCreateView.as_view(),
         name='category-create'),

    # JSON view
    path('json/', views.TicketJsonView.as_view(), name='ticket-list-json'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon.png' %}">
    <title>CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% include 'messages.html' %}

        {% block content %}
        
        {% endblock content %}
    </div>
    {% include "scripts.html" %}
</body>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 border-l-4
            {% if message.tags == 'success' %}
                bg-green-50 border-green-400
            {% elif message.tags == 'info' %}
                bg-blue-50 border-blue-400
            {% elif message.tags == 'warning' %}
                bg-yellow-50 border-yellow-400
            {% else %}
                bg-red-50 border-red-400
            {% endif %}        
            fade-out" id="message-{{ forloop.counter }}">
            <p class="text-sm
                {% if message.tags == 'success' %}
                    text-green-700
                {% elif message.tags == 'info' %}
                    text-blue-700
                {% elif message.tags == 'warning' %}
                    text-yellow-700
                {% else %}
                    text-red-700
                {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}


<script>
    // Automatically hide messages after 4 seconds
    document.addEventListener('DOMContentLoaded', function () {
        var messages = document.querySelectorAll('.fade-out');
        messages.forEach(function (message) {
            setTimeout(function () {
                message.style.display = 'none';
            }, 4000);
        });
    });
</script>

templates/navbar.html
<header class="text-gray-700 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a href="{% url 'tickets:ticket-list' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <img width="50" height="50" src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/external-crm-sales-flaticons-lineal-color-flat-icons-3.png" alt="external-crm-sales-flaticons-lineal-color-flat-icons-3"/>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if request.user.is_authenticated %}
        {% if request.user.is_organizer %}
        <a href="{% url 'landing:dashboard' %}" class="mr-5 hover:text-gray-900">Dashboard</a>
        <a href="{% url 'associates:associate-list' %}" class="mr-5 hover:text-gray-900">Associates</a>
        {% endif %}
        <a href="{% url 'tickets:ticket-list' %}" class="mr-5 hover:text-gray-900">Tickets</a>
        <a class="mr-5 hover:text-gray-900" href="{% url 'tickets:category-list' %}">Categories</a>        
        Logged in as: {{ request.user.username }}
        <a href="{% url 'landing:logout' %}" class="ml-3 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Logout
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
        {% else %}
        <a href="{% url 'landing:signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
        <a href="{% url 'landing:login' %}" class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Login
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
        {% endif %}
    </nav>    
  </div>
</header> 

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>